### PR TITLE
Development instructions and an easy way of starting the local swarm node

### PR DESCRIPTION
**Pull request by nietaki**

### CODE REVIEW

**Review by howleysv — APPROVED** [review]

**Comment by PaulLeCam** [comment]
@howleysv Is this OK to merge or does it need some changes regarding the git commit to checkout please, as you discussed with Louis?
Not directly related but I also think we could connect to swarm using the unix socket rather than the websocket if that could make things simpler? Eventually we should remove `--wsorigins '*'` or at least make it restrictive, no?

**Comment by howleysv** [comment]
@PaulLeCam Yes, right now I think it's referencing a bad commit sha but I want to test the code first.

I'm not sure the PSS functionality is exposed over IPC, is it?

What are the implications of setting the allowed origins like this? What should be it? IIRC the WS is bound to the loopback interface anyway.

**Comment by PaulLeCam** [comment]
So does it need to be merged to test the code? Why not test from the branch and merge to master once ready?

Regarding the WS should be all good if it's not possible to connect from elsewhere, but otherwise I think PSS works using IPC, it's HTTP that is not supported if I remember well.

**Comment by howleysv** [comment]
I think we have our wires crossed - I don't think it should be merged yet.

**Pull request merged**
